# Generated by Django 6.1.1 on 2026-10-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_current_stage'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=200, verbose_name='Название компонента')),
                ('flow_type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], default='expense', max_length=10, verbose_name='Тип')),
                ('amount_plan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Плановая сумма')),
                ('date_plan', models.DateField(blank=True, null=True, verbose_name='Плановая дата')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('paid', 'Оплачен')], default='planned', max_length=10, verbose_name='Статус')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.contractor', verbose_name='Подрядчик')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='orders.order', verbose_name='Заказ')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='orders.orderitem', verbose_name='Позиция товара (для группировки)')),
                ('substage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.substage', verbose_name='Подэтап')),
            ],
            options={
                'verbose_name': 'Плановый платеж',
                'verbose_name_plural': 'Плановые платежи',
                'ordering': ['order_item', 'date_plan'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], default='expense', max_length=10, verbose_name='Тип')),
                ('amount_fact', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Фактическая сумма')),
                ('date_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('payment_method', models.CharField(choices=[('cashless', 'Безнал'), ('cash', 'Наличные'), ('card', 'Карта')], default='cashless', max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен')], default='pending', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('budget_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.budgetitem', verbose_name='Плановый платеж')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Фактический платеж',
                'verbose_name_plural': 'Фактические платежи',
                'ordering': ['-date_fact'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('invoice', 'Счет на оплату'), ('act', 'Акт выполненных работ'), ('payment_order', 'Платежное поручение'), ('contract', 'Договор'), ('waybill', 'Накладная')], max_length=20, verbose_name='Тип документа')),
                ('number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='Файл')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order', verbose_name='Заказ')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.transaction', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date'],
            },
        ),
    ]
