# Generated by Django 6.1.1 on 2026-10-08 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0003_alter_order_current_stage'),
        ('partners', '0001_initial'),
        ('products', '0003_productcomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='status',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='source_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcomponent', verbose_name='Источник (компонент)'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.contractor', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='orders.orderitem', verbose_name='Позиция товара'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('invoice', 'Счет'), ('act', 'Акт'), ('payment_order', 'Платежка'), ('contract', 'Договор'), ('waybill', 'Накладная')], max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='finance.transaction', verbose_name='Платеж'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='budget_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.budgetitem', verbose_name='Плановый платеж'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.order', verbose_name='Заказ'),
        ),
    ]
