# Generated by Django 6.1.1 on 2026-10-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_budgetitem_status_budgetitem_source_component_and_more'),
        ('orders', '0004_alter_ordertypetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='orders.orderitem', verbose_name='Позиция товара'),
        ),
    ]
