# Generated by Django 6.1.1 on 2026-10-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_budgetitem_order_item'),
        ('orders', '0010_alter_orderitemcomponent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='source_component',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='item_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='orders.orderitemcomponent', verbose_name='Источник (компонент позиции)'),
        ),
    ]
