# Generated by Django 6.1.1 on 2026-10-09 08:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['name'], 'verbose_name': 'Подрядчик', 'verbose_name_plural': 'Подрядчики'},
        ),
        migrations.AddField(
            model_name='client',
            name='requisites',
            field=models.TextField(blank=True, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='payment_details',
            field=models.TextField(blank=True, verbose_name='Реквизиты оплаты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=5, verbose_name='Ставка НДС (например, 0.20)'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг надёжности (1-5)'),
        ),
    ]
