# Generated by Django 6.1.1 on 2026-10-09 09:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_client_options_alter_contractor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=5, verbose_name='Наценка по умолчанию'),
        ),
    ]
