# Generated by Django 6.1.1 on 2026-10-08 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_current_stage'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('doc_type', models.CharField(choices=[('invoice', 'Счет'), ('act', 'Акт'), ('contract', 'Договор'), ('kp', 'КП (Коммерческое предложение)'), ('waybill', 'Накладная')], max_length=20, verbose_name='Тип документа')),
                ('url', models.URLField(verbose_name='Ссылка на файл в облаке')),
                ('description', models.TextField(blank=True, verbose_name='Описание / Подсказка')),
                ('order_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ordertype', verbose_name='Тип заказа (пусто = универсальный)')),
                ('substage_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.substagetemplate', verbose_name='Подэтап (пусто = в любой момент)')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['doc_type', 'name'],
            },
        ),
    ]
