# Generated by Django 6.1.1 on 2026-10-07 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0002_remove_supplierproduct_contractor_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип заказа',
                'verbose_name_plural': 'Типы заказов',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название этапа')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deadline_plan', models.DateField(verbose_name='Плановый дедлайн')),
                ('deadline_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата завершения')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма по договору')),
                ('expenses_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма расходов')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.client', verbose_name='Заказчик')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.ordertype', verbose_name='Тип заказа')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.stage', verbose_name='Текущий этап')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.ourproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_stages', to='orders.order', verbose_name='Заказ')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Этап заказа',
                'verbose_name_plural': 'Этапы заказов',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SubstageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('offset_days', models.IntegerField(default=0, verbose_name='Смещение дедлайна (дней от старта заказа)')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordertype', verbose_name='Тип заказа')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Шаблон подэтапа',
                'verbose_name_plural': 'Шаблоны подэтапов',
            },
        ),
        migrations.CreateModel(
            name='Substage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('status', models.CharField(choices=[('not_started', 'Не начата'), ('in_progress', 'В работе'), ('completed', 'Выполнена')], default='not_started', max_length=20, verbose_name='Статус')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substages', to='orders.order', verbose_name='Заказ')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.stage', verbose_name='Этап')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.substagetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Подэтап',
                'verbose_name_plural': 'Подэтапы',
                'ordering': ['deadline'],
            },
        ),
    ]
