# Generated by Django 6.1.1 on 2026-10-07 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substage',
            options={'ordering': ['order_index'], 'verbose_name': 'Подэтап', 'verbose_name_plural': 'Подэтапы'},
        ),
        migrations.AlterModelOptions(
            name='substagetemplate',
            options={'verbose_name': 'Шаблон задачи', 'verbose_name_plural': 'Шаблоны задач'},
        ),
        migrations.RemoveField(
            model_name='substagetemplate',
            name='offset_days',
        ),
        migrations.RemoveField(
            model_name='substagetemplate',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='substagetemplate',
            name='stage',
        ),
        migrations.AddField(
            model_name='substage',
            name='duration_days',
            field=models.IntegerField(default=1, verbose_name='Длительность (дней)'),
        ),
        migrations.AddField(
            model_name='substage',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='Порядок в заказе'),
        ),
        migrations.AddField(
            model_name='substagetemplate',
            name='default_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.stage', verbose_name='Этап по умолчанию'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.stage', verbose_name='Текущий этап'),
        ),
        migrations.CreateModel(
            name='OrderTypeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField(default=1, verbose_name='Длительность задачи (дней)')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок выполнения')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordertype', verbose_name='Тип заказа')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.substagetemplate', verbose_name='Шаблон задачи')),
            ],
            options={
                'verbose_name': 'Настройка задачи для типа',
                'verbose_name_plural': 'Настройки задач для типов',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='ordertype',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='order_types', through='orders.OrderTypeTemplate', to='orders.substagetemplate', verbose_name='Базовые задачи для этого типа'),
        ),
        migrations.DeleteModel(
            name='OrderStage',
        ),
    ]
