# Generated by Django 6.1.1 on 2026-10-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_substage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.stage', verbose_name='Текущий этап (авто)'),
        ),
    ]
