# Generated by Django 6.1.1 on 2026-10-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_current_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertypetemplate',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='substage',
            options={'ordering': ['order_index']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='expenses_amount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вариант (цвет/размер)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Финальный этап'),
        ),
        migrations.AddField(
            model_name='substagetemplate',
            name='hint',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.stage', verbose_name='Текущий этап'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='templates',
            field=models.ManyToManyField(blank=True, through='orders.OrderTypeTemplate', to='orders.substagetemplate', verbose_name='Базовые задачи'),
        ),
        migrations.AlterField(
            model_name='ordertypetemplate',
            name='duration_days',
            field=models.IntegerField(default=1, verbose_name='Длительность (дней)'),
        ),
        migrations.AlterField(
            model_name='ordertypetemplate',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='substage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.stage', verbose_name='Этап'),
        ),
    ]
