# Generated by Django 6.1.1 on 2026-10-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordertypetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Наценка (%)'),
        ),
    ]
