# Generated by Django 6.1.1 on 2026-10-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_markup_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contract_amount',
        ),
    ]
