# Generated by Django 6.1.1 on 2026-10-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_contract_amount'),
        ('products', '0004_ourproduct_auto_calculate_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Себестоимость (рассчитана)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу (итог)'),
        ),
        migrations.CreateModel(
            name='OrderItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу (на момент заказа)')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='orders.orderitem', verbose_name='Позиция заказа')),
                ('substage_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.substagetemplate', verbose_name='Шаблон подэтапа')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.supplierproduct', verbose_name='Товар/услуга поставщика')),
            ],
            options={
                'verbose_name': 'Компонент позиции',
                'verbose_name_plural': 'Компоненты позиций',
            },
        ),
    ]
