# Generated by Django 6.1.1 on 2026-10-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('orders', '0007_orderitem_cost_value_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substage',
            options={'ordering': ['stage__order_index', 'index_in_stage'], 'verbose_name': 'Подэтап', 'verbose_name_plural': 'Подэтапы'},
        ),
        migrations.RemoveField(
            model_name='substage',
            name='order_index',
        ),
        migrations.AddField(
            model_name='substage',
            name='index_in_stage',
            field=models.IntegerField(default=0, verbose_name='Номер внутри этапа'),
        ),
        migrations.AddField(
            model_name='substagetemplate',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='substage_templates', to='documents.documenttemplate', verbose_name='Шаблоны документов'),
        ),
    ]
