# Generated by Django 6.1.1 on 2026-10-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('orders', '0008_alter_substage_options_remove_substage_order_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemcomponent',
            options={'verbose_name': 'Подэтап', 'verbose_name_plural': 'Подэтапы'},
        ),
        migrations.RemoveField(
            model_name='substagetemplate',
            name='documents',
        ),
        migrations.CreateModel(
            name='SubstageTemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttemplate', verbose_name='Шаблон документа')),
                ('substage_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_documents', to='orders.substagetemplate', verbose_name='Шаблон подэтапа')),
            ],
            options={
                'verbose_name': 'Документ шаблона подэтапа',
                'verbose_name_plural': 'Документы шаблона подэтапа',
                'unique_together': {('substage_template', 'document_template')},
            },
        ),
    ]
