# Generated by Django 6.1.1 on 2026-10-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitemcomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemcomponent',
            options={'verbose_name': 'Компонент позиции', 'verbose_name_plural': 'Компоненты позиций'},
        ),
        migrations.AlterModelOptions(
            name='ordertypetemplate',
            options={'ordering': ['order_index', 'id'], 'verbose_name': 'Задача типа заказа', 'verbose_name_plural': 'Задачи типа заказа'},
        ),
        migrations.AlterModelOptions(
            name='substage',
            options={'ordering': ['stage__order_index', 'index_in_stage', 'id'], 'verbose_name': 'Подэтап', 'verbose_name_plural': 'Подэтапы'},
        ),
        migrations.AlterModelOptions(
            name='substagetemplate',
            options={'ordering': ['default_stage__order_index', 'name'], 'verbose_name': 'Шаблон задачи', 'verbose_name_plural': 'Шаблоны задач'},
        ),
        migrations.AddField(
            model_name='substage',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.stage', verbose_name='Текущий этап (авто)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Если у товара есть спецификация - считается сама (себестоимость + наценка). Если спецификации нет - вводится вручную.', max_digits=10, verbose_name='Цена за единицу (итог)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitemcomponent',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество на 1 шт.'),
        ),
        migrations.AlterField(
            model_name='ordertypetemplate',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Длительность (дней)'),
        ),
        migrations.AlterField(
            model_name='ordertypetemplate',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='substage',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Длительность (дней)'),
        ),
        migrations.AlterField(
            model_name='substage',
            name='index_in_stage',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер внутри этапа'),
        ),
        migrations.AlterField(
            model_name='substagetemplate',
            name='default_stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.stage', verbose_name='Этап'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substagetemplate',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Подсказка менеджеру'),
        ),
        migrations.AddConstraint(
            model_name='ordertypetemplate',
            constraint=models.UniqueConstraint(fields=('order_type', 'template'), name='unique_template_per_order_type'),
        ),
    ]
