# Generated by Django 6.1.1 on 2026-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи без НДС')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='Минимальный тираж (шт.)')),
                ('production_days', models.IntegerField(default=1, verbose_name='Срок производства (дней)')),
            ],
            options={
                'verbose_name': 'Наш товар',
                'verbose_name_plural': 'Наши товары',
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=200, verbose_name='Название поставщика')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара/услуги')),
                ('product_type', models.CharField(blank=True, max_length=100, verbose_name='Тип (Одежда, Печать, Упаковка)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена закупки без НДС')),
                ('lead_time_days', models.IntegerField(default=1, verbose_name='Срок поставки (дней)')),
            ],
            options={
                'verbose_name': 'Товар поставщика',
                'verbose_name_plural': 'Товары поставщиков',
            },
        ),
    ]
