# Generated by Django 6.1.1 on 2026-10-07 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='contractor_name',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.contractor', verbose_name='Поставщик'),
        ),
    ]
