# Generated by Django 6.1.1 on 2026-10-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_current_stage'),
        ('products', '0002_remove_supplierproduct_contractor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество на 1 шт. нашего товара')),
                ('our_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.ourproduct', verbose_name='Наш товар')),
                ('substage_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.substagetemplate', verbose_name='Шаблон подэтапа (когда оплачивать)')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.supplierproduct', verbose_name='Товар/услуга поставщика')),
            ],
            options={
                'verbose_name': 'Компонент товара',
                'verbose_name_plural': 'Компоненты товаров',
            },
        ),
    ]
