# Generated by Django 6.1.1 on 2026-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproduct',
            name='auto_calculate_price',
            field=models.BooleanField(default=True, verbose_name='Автоматически считать базовую цену по спецификации'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи без НДС (базовая)'),
        ),
    ]
