# Generated by Django 6.1.1 on 2026-10-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ourproduct_auto_calculate_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourproduct',
            name='auto_calculate_price',
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Минимальный тираж (шт.)'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='production_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Срок производства (дней)'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая цена продажи без НДС (справочно)'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Срок поставки (дней)'),
        ),
    ]
